package StockExchangeEngine;

import AutoGenerated.RizpaStockExchangeDescriptor;
import Stocks.Stock;
import Transaction.ITransaction;
import Transaction.Transaction;

import java.io.IOException;
import java.util.List;
import java.util.Map;

public interface IStockEngine {

    public Map<String,Stock> getStocks();
    public boolean getXmlContent(StringBuilder msg, String path);
    //public loadStocks();
    List<ITransaction> getTransactionlist();
    public boolean findTransaction(String stockName, double limit, int amountForTransaction);
    public void addPendingSell(Stock stock);
    public void addPendingPurchase(Stock stock);
    public void preformTransaction(ITransaction toSell,ITransaction toBuy);
    public void presentAllStocksTransactions() throws  IOException;
}
