package xmlRizpaDataExtractor;

import autoGeneratedWeb.*;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

public class XmlRizpaDataExtractor {

    public static final String packageToReadFrom = "autoGeneratedWeb";

   public static  RizpaStockExchangeDescriptor getStocks(String path, AtomicBoolean hasSameCompany, AtomicBoolean hasSameName,AtomicBoolean hasInValidStock)
   {
       RizpaStockExchangeDescriptor stocksDescriptor = null;
       try
       {
           InputStream inputStream = new FileInputStream(new File(path));
           stocksDescriptor = deserializeFrom(inputStream);
       }
       catch (JAXBException | FileNotFoundException e) {
           e.printStackTrace();
       }

       if(!checkIfContentIsValid(stocksDescriptor,hasSameCompany,hasSameName,hasInValidStock))
       {
           stocksDescriptor = null;
       }

       return stocksDescriptor;
   }
    public static  RizpaStockExchangeDescriptor getStocks(InputStream inputStream, AtomicBoolean hasSameCompany, AtomicBoolean hasSameName,AtomicBoolean hasInValidStock)
    {
        RizpaStockExchangeDescriptor stocksDescriptor = null;
        try
        {
            stocksDescriptor = deserializeFrom(inputStream);
        }
        catch (JAXBException  e) {
            e.printStackTrace();
        }

        if(!checkIfContentIsValid(stocksDescriptor,hasSameCompany,hasSameName,hasInValidStock))
        {
            stocksDescriptor = null;
        }

        return stocksDescriptor;
    }

   private static RizpaStockExchangeDescriptor deserializeFrom(InputStream inputStream) throws JAXBException
   {
       JAXBContext jc = JAXBContext.newInstance(packageToReadFrom);
       Unmarshaller um =jc.createUnmarshaller();
       Object unmarshaller = um.unmarshal(inputStream);
       return (RizpaStockExchangeDescriptor)unmarshaller;
   }

   public static boolean checkIfContentIsValid(RizpaStockExchangeDescriptor rsed, AtomicBoolean hasSameCompany, AtomicBoolean hasSameName,AtomicBoolean hasInValidStock)
   {   Map<String,String> companyNames = new HashMap<>();
       Map<String,RseStock> mapStocks = new HashMap<>();
       List<RseStock> stocks = rsed.getRseStocks().getRseStock();
       List<RseItem> holdings = rsed.getRseHoldings().getRseItem();
       boolean isValidFormat;
       for (RseStock stock:stocks)
       {
            if(mapStocks.containsKey(stock.getRseSymbol()))
           hasSameName.compareAndSet(false,true) ;
            if( companyNames.containsKey(stock.getRseCompanyName()))
           hasSameCompany.compareAndSet(false,true) ;;;
            mapStocks.put(stock.getRseSymbol(),stock);
            companyNames.put(stock.getRseCompanyName(),stock.getRseCompanyName());
       }


       for (RseItem item:holdings) {
           if (!mapStocks.containsKey(item.getSymbol()))
           {
               hasInValidStock.compareAndSet(false,true);
               break;
           }
       }
          isValidFormat = !hasSameName.get() && !hasSameCompany.get() && !hasInValidStock.get();

            return isValidFormat;
        }
}
